name: update-flake-lock
on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at 00:00

permissions:
  contents: write

jobs:
  lockfile:
    name: Update the Nix lockfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          nix_on_tmpfs: true

      - name: Update flake.lock
        run: nix flake update -L --show-trace

      - name: Commit Changes
        id: commit
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add flake.lock
          git commit -m "[Automated] bump lockfile"

      - name: Test Changes
        if: steps.commit.outcome == 'success'
        run: nix flake check -L --show-trace

      - name: Push changes
        if: steps.commit.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
